[package]
name = "s3dlio"
version = "0.3.4"
edition = "2024"

[lib]
name = "s3dlio"
crate-type = ["cdylib", "rlib"]      # cdylib → Python wheel, rlib → normal Rust

[package.metadata.maturin]
features = ["extension-module"]

[[bin]]
name = "s3-cli"
path = "src/bin/cli.rs"

[dependencies]
aws-config         = "^1"
aws-sdk-s3         = "^1"

# Optional: Add env_logger and log for debugging output from SDK/client
env_logger = "0.11"
log = "0.4"

# --- async / net stack ----------------------------------------------------
tokio   = { version = "1", features = ["full"] }
#tokio = { version = "1.45.0", features = ["full"] }
hyper   = { version = "^1", features = ["client"] }		# ← Upgraded
hyper-rustls = "^0.27"                                		# ← matches hyper ^1
aws-smithy-http-client = { version = "1.0.1", features = ["rustls-aws-lc"] }
rustls  = { version = "^0.23" }					# ← matches hyper‑rustls 0.27
webpki-roots = "^0.26"

# --- util / CLI / etc. ----------------------------------------------------
once_cell = "^1.19"
dotenvy   = "^0.15"
anyhow    = "^1"
thiserror = "1.0"
clap      = { version = "4", features = ["derive"] }
regex     = "1.11"
futures   = "^0.3"
rand      = "^0.9"
tempfile  = "^3.20"
tfrecord  = "^0.15"
bytes     = "^1.10"
#zip       = { version = "^0.5", default-features = false }
zip       = { version = "^2.1", default-features = false }

# Not certain which hdf5 gives best set of features
#hdf5 = { package = "hdf5-metno", version = "0.10.1" }
hdf5-metno = "^0.10"
hdf5-metno-sys = "^0.10"

# -------- Python bindings ----------
#pyo3         = { version = "^0.20", features = ["extension-module"] }
#pyo3-asyncio = { version = "^0.20", features = ["tokio-runtime"] }
#numpy        = "^0.20"

pyo3         = { version = "^0.25", features = ["extension-module"] }
pyo3-async-runtimes = { version = "^0.25", features = ["tokio-runtime"] }
numpy        = "^0.25"
ndarray      = "^0.15"
ndarray-npy = "^0.8"

# Other
rayon       = "^1.10"
chrono      = "^0.4"
#io          = "^0.02"
io          = "^0.0"
crc32fast   = "^1.4"
glob        = "^0.3"

async-trait  = "^0.1"
async-stream = "^0.3"
futures-core = "^0.3"
futures-util = "^0.3"

zstd         = "^0.13"
humantime    = "^2.2"


[dev-dependencies]
tokio         = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-util  = "^0.3"
async-trait   = "^0.1"   # needed by the mock datasets

[features]
default = []
extension-module = []     # suppresses the cfg warning when building the wheel

