[package]
name = "s3dlio"
version = "0.3.1"
edition = "2024"

[lib]
name = "s3dlio"
crate-type = ["cdylib", "rlib"]      # cdylib → Python wheel, rlib → normal Rust

[package.metadata.maturin]
features = ["extension-module"]

[[bin]]
name = "s3-cli"
path = "src/bin/cli.rs"

[dependencies]
aws-config         = "^1"
aws-sdk-s3         = "^1"
#aws-config = "1.6.2"
#aws-sdk-s3 = "1.84.0"

# Optional: Add env_logger and log for debugging output from SDK/client
env_logger = "0.11"
log = "0.4"


# --- async / net stack ----------------------------------------------------
tokio   = { version = "1", features = ["full"] }
#tokio = { version = "1.45.0", features = ["full"] }
hyper   = { version = "^1", features = ["client"] }		# ← Upgraded
hyper-rustls = "^0.27"                                		# ← matches hyper ^1
aws-smithy-http-client = { version = "1.0.1", features = ["rustls-aws-lc"] }
rustls  = { version = "^0.23" }					# ← matches hyper‑rustls 0.27
webpki-roots = "^0.26"

# --- util / CLI / etc. ----------------------------------------------------
once_cell = "^1.19"
dotenvy   = "^0.15"
anyhow    = "^1"
clap      = { version = "4", features = ["derive"] }
regex     = "1.11"
futures   = "^0.3"
rand      = "0.9.0"

# -------- Python bindings ----------
pyo3        = { version = "^0.20", features = ["extension-module"] }
pyo3-asyncio = { version = "^0.20", features = ["tokio-runtime"] }
numpy       = "^0.20"
ndarray     = "^0.15"
ndarray-npy = "^0.8"
zip         = "^0.6"
rayon = "1.10.0"
chrono = "0.4.41"
io = "0.0.2"
glob = "0.3.2"


[features]
default = []
extension-module = []     # suppresses the cfg warning when building the wheel

