name: Sync from public upstream

on:
  schedule:
    - cron: '15 6 * * *'    # Runs daily at 6:15am UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private mirror
        uses: actions/checkout@v3
        with:
          repository: russfellows/dlio_s3_rust
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Pull upstream
        run: |
          git remote add upstream https://github.com/russfellows/dlio_s3_rust.git
          git fetch upstream
          git merge --no-edit upstream/main

      - name: Push changes
        run: git push origin main
